# Site settings
title: Erivaldo Alves de Oliveira Jr
description: Curriculo Erivaldo Jr
favicon: /assets/img/foto.jpg
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Erivaldo Alves de Oliveira Jr
  title: Devops
  address: Bahia, Brasil
  email: eaojunior1@gmail.com
  link: http://eaojunior.github.io
  weibo:
  github: eaojunior
  linkedin: 
  twitter: 
  gavatar: /assets/img/foto.jpg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Soledade Tecnologia
      location: Bahia, Brasil
      title: Developer PHP, Android and Oracle
      started: 2015
      duration: (12/2015 - Present)
      description: 
    - work2:
      company: Simetria Tecnologia
      location: Bahia, Brasil
      title: Devops
      started: 2014
      duration: (11/2014 - 12/2015)
      description: 
  educationHistory:
    - education1:
      organization: Northeastern University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Portuguese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: PHP
      percentage: 95%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 90%
    - skill4:
      name: Android
      percentage: 70%
    - skill5:
      name: Apache
      percentage: 90%
    - skill6:
      name: HTTPD
      percentage: 90%
    - skill7:
      name: Bind
      percentage: 95%
    - skill8:
      name: Iptables
      percentage: 85%
    - skill9:
      name: HTB
      percentage: 80%