# Site settings
title: Erivaldo Alves de Oliveira Jr
description: Curriculo Erivaldo Jr
favicon: /assets/img/foto.jpg
baseurl: 
url: http://eaojunior.github.io
rss_url: /pages/atom.xml
google_analytics: UA-78083739-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Erivaldo Alves de Oliveira Jr
  title: Devops
  address: Bahia, Brasil
  email: eaojunior1@gmail.com
  link: http://eaojunior.github.io
  weibo:
  github: eaojunior
  linkedin: 
  twitter: 
  gavatar: /assets/img/foto.jpg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Soledade Tecnologia
      location: Bahia, Brasil
      title: PHP Developer, Android Developer and Oracle BI
      started: 2015
      duration: (12/2015 - Present)
      description: 
    - work2:
      company: Simetria Tecnologia
      location: Bahia, Brasil
      title: Devops
      started: 2014
      duration: (11/2014 - 12/2015)
      description: 
  educationHistory:
    - education1:
      organization: Estácio FIB
      location: Bahia, Brasil
      degree: Bachelor
      major: Software Engineering
      started: 2014
      duration: (2014 - 2018)
      description:
  languages:
    - language1:
      name: Portuguese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: PHP
      percentage: 95%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 90%
    - skill4:
      name: Android
      percentage: 70%
  otherSkills:
    - skill1:
      name: Apache
      percentage: 90%
    - skill2:
      name: HTTPD
      percentage: 90%
    - skill3:
      name: Bind
      percentage: 95%
    - skill4:
      name: Iptables
      percentage: 85%
    - skill5:
      name: HTB
      percentage: 80%